# Name of our action
name: 'Chromatic'
# The event that will trigger the action
on: push

# What the action will do
jobs:
  tests:
    # The operating system it will run on
    runs-on: ubuntu-latest
    # The list of steps that the action will go through
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn
      # 👇 Adds Chromatic as a step in the workflow
    - name: Publish to Chromatic
      uses: chromaui/action@v1
      # Chromatic GitHub Action options
      with:
        # 👇 Chromatic projectToken, refer to the manage page to obtain it.
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}